
name: TEST Release

on:
    push:
      tags:
        - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: ubuntu:jammy

    strategy:
      matrix:
        include:
          - NAME: name1
            VERSION: 1.0.0
          - NAME: name2
            VERSION: 1.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and compress database
        if: github.event.release.tag_name == "v${{ matrix.VERSION }}"
        run: |
          apt-get update
          apt-get -y install tar gzip gh
          mkdir ${{ matrix.NAME }}
          echo 'yo ${{ matrix.NAME }}' > ${{ matrix.NAME }}/test.txt
          tar cvzf ${{ matrix.NAME }}.tar.gz ${{ matrix.NAME }}

      - name: Create GitHub Release
        shell: bash
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh release create ${{ github.ref }} ${{ matrix.NAME }}.tar.gz --title "Release ${{ github.ref }}" --notes "Release for ${{ matrix.NAME }} version ${{ matrix.VERSION }}"